/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author gustavo.araujo
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jLabelCadastroSenha = new javax.swing.JLabel();
        jLabel1ConformacaoCadastroSenha = new javax.swing.JLabel();
        jPasswordFieldCadastroSenha = new javax.swing.JPasswordField();
        jPasswordFieldConformacaoCadastroSenha = new javax.swing.JPasswordField();
        jLabelCadastroEmail = new javax.swing.JLabel();
        jTextFieldCadastroEmail = new javax.swing.JTextField();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNomeUsuario.setText("Nome:");
        getContentPane().add(jLabelNomeUsuario);
        jLabelNomeUsuario.setBounds(70, 50, 40, 30);

        jButton1.setText("Concluir ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 120, 23);

        jTextFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeUsuario);
        jTextFieldNomeUsuario.setBounds(120, 60, 200, 20);

        jLabelCadastroSenha.setText("Senha:");
        getContentPane().add(jLabelCadastroSenha);
        jLabelCadastroSenha.setBounds(70, 130, 34, 14);

        jLabel1ConformacaoCadastroSenha.setText("Conforme a senha:");
        getContentPane().add(jLabel1ConformacaoCadastroSenha);
        jLabel1ConformacaoCadastroSenha.setBounds(10, 170, 100, 14);

        jPasswordFieldCadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCadastroSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldCadastroSenha);
        jPasswordFieldCadastroSenha.setBounds(120, 130, 200, 20);
        getContentPane().add(jPasswordFieldConformacaoCadastroSenha);
        jPasswordFieldConformacaoCadastroSenha.setBounds(120, 170, 200, 20);

        jLabelCadastroEmail.setText("E-mail:");
        getContentPane().add(jLabelCadastroEmail);
        jLabelCadastroEmail.setBounds(70, 90, 32, 14);

        jTextFieldCadastroEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCadastroEmail);
        jTextFieldCadastroEmail.setBounds(120, 90, 200, 20);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelaLogin.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 500, 300);

        setSize(new java.awt.Dimension(516, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeUsuarioActionPerformed

    private void jTextFieldCadastroEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroEmailActionPerformed

    private void jPasswordFieldCadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldCadastroSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaConfirmacaoCadastro confirmacao = new TelaConfirmacaoCadastro();
        confirmacao.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1ConformacaoCadastroSenha;
    private javax.swing.JLabel jLabelCadastroEmail;
    private javax.swing.JLabel jLabelCadastroSenha;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPasswordField jPasswordFieldCadastroSenha;
    private javax.swing.JPasswordField jPasswordFieldConformacaoCadastroSenha;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField jTextFieldCadastroEmail;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
